CREATE COLUMN TABLE "HANA_DIM"."ZT_MAP_ADDR" ("LOCATION" NVARCHAR(60),
	 "LNG" NVARCHAR(30),
	 "LAT" NVARCHAR(30),
	 "COUNTRY" NVARCHAR(40),
	 "PROVINCE" NVARCHAR(40),
	 "CITY" NVARCHAR(40),
	 "DISTRICT" NVARCHAR(40),
	 "STREET" NVARCHAR(200),
	 "TOWNSHIP" NVARCHAR(40),
	 "INS_DATE" NVARCHAR(8),
	 PRIMARY KEY INVERTED VALUE ("LOCATION")) UNLOAD PRIORITY 5 AUTO MERGE
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."LOCATION" is '初始经纬度'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."LNG" is '解析后对应经度'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."LAT" is '解析后对应纬度'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."COUNTRY" is '国家'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."PROVINCE" is '省'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."CITY" is '市'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."DISTRICT" is '区'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."STREET" is '街道'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."TOWNSHIP" is '乡'
;
COMMENT ON COLUMN "HANA_DIM"."ZT_MAP_ADDR"."INS_DATE" is '信息录入日期'
;